dependencies:
  - bokeh==3.3.4
  - ipython==8.21.0
  - ipywidgets==8.1.1
  - matplotlib==3.8.2
  - networkx==3.2.1
  - numpy==1.26.4
  - pandas==2.2.1
  - plotly==5.18.0
  - tqdm==4.66.1
  - watermark==2.4.3
