dependencies:
  - bokeh==3.2.1
  - ipython==8.12.3
  - ipywidgets==8.0.4
  - matplotlib==3.7.2
  - networkx==3.1
  - numpy==1.23.5
  - pandas==2.0.3
  - plotly==5.9.0
  - tqdm==4.65.0
  - watermark==2.4.3
